#!/bin/bash

long_usage_message="usage: $(basename $0) container-upgrade [<name>] [<action>]
Check if container needs to be upgraded and either: report it's upgrade status
or stop, remove and re-create the container so it gets the updates. See also
image-upgrade.

Arguments
  <name> - The container name you want to upgrade or '--all' to update all containers.
   All is the default. When using all, the databases will be upgraded first to avoid
   linking problems when the sites are created.
  <action> - Whether to 'check' 'run' upgrade. Check is the default." 

long_check_args "$2" "$#" 0

containers="$2"
action="$3"

if [ -z "$containers" -o "$containers" = "--all" ]; then
  containers=$(ls "${LONG_SRV}/services/databases/"; ls "${LONG_SRV}/services/sites")
fi

if [ -z "$action" ]; then
  action=check
fi

if [ "$action" != "check" -a "$action" != "run" ]; then
  long_die "Action should be either check or run." 
fi

if [ "$action" = "run" ]; then
  long_prompt "Stopping, removing and re-creating containers needing upgrades."
  if [ "$reply" != "y" ]; then
    long_die "Not proceeding."
  fi
fi

for container in $containers; do
  ! long_container_exists "$container" && continue

  if [ "$action" = "check" ]; then
    if long_needs_upgrade "$container"; then
      long_log "%s: needs upgrade." info "$container"
    else
      long_log "%s: does not need upgrade.\n" info "$container"
    fi
  elif [ "$action" = "run" ]; then
    # This command only runs if container needs an upgrade.
    long_upgrade_container "$container"
  fi
done
