#!/bin/bash

long_usage_message="usage: $(basename $0) db-list [<sibling>]
List all databases on all siblings, or a given sibling.

Arguments
  <sibling> - Optionally, limit to the given sibling."

long_check_args "$2" "$#" 0

siblings="$2"

long_set_dbs "$siblings"

