#!/bin/bash

# See: https://stackoverflow.com/questions/67093/how-do-i-rename-a-mysql-database-change-schema-name

long_usage_message="usage: $(basename $0) db-rename <oldname> <newname>
Rename a database.

Arguments
  <oldname> - old name 
  <newname> - new name."

long_check_args "$2" "$#" 2

oldname="$2"
newname="$3"

if ! long_check_alpha_numeric "$oldname"; then
  long_die "Your oldname should only contain alpha numeric characters."
fi

if ! long_check_alpha_numeric "$newname"; then
  long_die "Your newname should only contain alpha numeric characters."
fi

long_prompt "This will drop the database named %s if it exists. Continue? " "$newname"
if [ "$reply" != "y" ]; then
  long_die "Not proceeding."
fi

root_query() {
  sql="$1"
  tmp=$(mktemp)
  echo "$sql" > "$tmp"
  long_execute_root_query mysqlhost "$tmp"
  rm "$tmp"
}
site_query() {
  site="$1"
  sql="$2"
  if [ -f "$sql" ]; then
    cat "$sql"
    long_execute_site_query "$site" "$sql"
  else
    tmp=$(mktemp)
    echo "$sql" > "$tmp"
    cat "$tmp"
    long_execute_site_query "$site" "$tmp"
    rm "$tmp"
  fi
}
# Ensure we don't have a naming conflict.
root_query "DROP DATABASE IF EXISTS $newname"

# Get the basics from the old table - table names, views names, and triggers/events, etc.
character_set=$(root_query "SELECT default_character_set_name FROM information_schema.SCHEMATA WHERE schema_name = '$oldname'")
tables=$(root_query "SELECT TABLE_NAME FROM information_schema.tables WHERE table_schema='$oldname' AND TABLE_TYPE='BASE TABLE'")
views=$(root_query "SELECT TABLE_NAME FROM information_schema.tables WHERE table_schema='$oldname' AND TABLE_TYPE='VIEW'")
triggers=$(site_query "$oldname" "SHOW TRIGGERS\G" | grep Trigger: | awk '{print $2}')
if [ -z "$tables" ]; then
  long_die "Error retrieving tables from %s" 1 "$oldname"
fi

# If we have views, dump them to a file
if [ -n "$views" ]; then
  views_tmp=$(mktemp --suffix .sql)
  long_dump_database "$oldname" "$views_tmp" $views
  # Rename the definer to remove the d8 part.
  sed -i 's/d8`@/`@/g' "$views_tmp"
fi

# Dump all manner of routines, triggers, events, etc to a file.
triggers_tmp=$(mktemp --suffix .sql)
mysqldump --defaults-file="${LONG_SRV}/etc/my.cnf"  --no-data --no-create-info --routines --events "$oldname" > "$triggers_tmp"
# Rename the definer to remove the d8 part.
sed -i 's/d8`@/`@/g' "$triggers_tmp"

# If we have triggers, drop them to avoid having them go off while we rename the tables.
for trigger in $triggers; do
    site_query "$oldname" "DROP TRIGGER $trigger"
done

# Create the new database
root_query "CREATE database $newname DEFAULT CHARACTER SET $character_set"

# Rename each table.
for table in $tables; do
  root_query "SET FOREIGN_KEY_CHECKS=0; RENAME TABLE ${oldname}.${table} to ${newname}.${table}"
done

# Import the views.
if [ -n "$views" ]; then
    site_query "$newname" "$views_tmp"
    rm "$views_tmp"
fi

# Import the triggers.
site_query "$newname" "$triggers_tmp"
rm "$triggers_tmp"

# Check to see if we missed anything.
remaining_tables=$(root_query "SELECT TABLE_NAME FROM information_schema.tables WHERE table_schema='$oldname' and TABLE_TYPE='BASE TABLE'")
if [ -n "$remaining_tables" ]; then
  long_log "Tables remain in old database: %s" error "$remaining_tables"
fi
