#!/bin/bash

long_usage_message="usage: $(basename $0)
Start the phpmyadmin container and all linked db containers."

long_check_args "$2" "$#" 0

# Start.
long_container_up phpmyadmin
long_nginx_reload
