#!/bin/bash

long_usage_message="usage: $(basename $0) <path>
Build a new platform based on the given makefile.

Arguments:
 <path> path to a drush make file." 

long_check_args "$2" "$#" 1

base=${LONG_SRV}/platforms
makefile_path="$2"

if [ ! -f "$makefile_path" ]; then
	long_die "Can't find makefile path: %s\n"  1 "$makefile_path"
	exit
fi

makefile=$(basename "$makefile_path")
source_platform_path="${base}/${makefile}"
source_platform_path_temp=$(mktemp -d --tmpdir="$base")

long_log "Creating platform." info
cd "$source_platform_path_temp"
$LONG_DRUSH -q -y make "$makefile_path"

# Do a sanity check. drush make will not leave any files in the target
# if just one download failed.

if [ ! -f "${source_platform_path_temp}/index.php" ]; then
  long_die "Failed to make the site!"
fi

# Hackish way to get symlink to wkhtmltopdf - which is needed if anyone
# enables the print module
ln -s /usr/bin/wkhtmltopdf "${source_platform_path_temp}/sites/all/libraries/"

# The CiviCRM extensions directory is in sites/all/extensions, which is
# sensible. However, CiviCRM will want to create a tmp and cache directory
# in that directory to keep information about the extensions for the given
# site. The php user can't write to this directory, so we create a symlink
# to the default sites directory where the PHP user can write.
ln -s ../../../default/private/extensions/tmp  \
  "${source_platform_path_temp}/sites/all/extensions/tmp"
ln -s ../../../default/private/extensions/cache  \
  "${source_platform_path_temp}/sites/all/extensions/cache"

long_log "Running GenCode.php..." info
target_path="${source_platform_path_temp}/sites/all/modules/civicrm/xml"
[ ! -d "$target_path" ] && long_die "The xml directory on the platform doesn't exist."
cd "$target_path"
php GenCode.php > /dev/null

delete="sites/all/modules/civicrm/bin/setup.sh
sites/all/modules/civicrm/distmaker
sites/all/modules/civicrm/.gitignore
sites/all/modules/civicrm/header-afl.txt
sites/all/modules/civicrm/header-agpl.txt
sites/all/modules/civicrm/header.sql
sites/all/modules/civicrm/header.tpl
sites/all/modules/civicrm/header.txt
sites/all/modules/civicrm/packages/amavisd-new
sites/all/modules/civicrm/packages/git-footnote
sites/all/modules/civicrm/packages/_ORIGINAL_
sites/all/modules/civicrm/packages/PhpDocumentor
sites/all/modules/civicrm/packages/PHPUnit
sites/all/modules/civicrm/packages/SeleniumRC
sites/all/modules/civicrm/packages/SymfonyComponents
sites/all/modules/civicrm/sql/civicrm_arms_sample_data.sql
sites/all/modules/civicrm/sql/GenerateData.php
sites/all/modules/civicrm/sql/GenerateData.README
sites/all/modules/civicrm/sql/GenerateGroups.php
sites/all/modules/civicrm/sql/GenerateMailing.php
sites/all/modules/civicrm/sql/GenerateReportData.php
sites/all/modules/civicrm/sql/README.txt
sites/all/modules/civicrm/sql/sample_data_pl.xml
sites/all/modules/civicrm/sql/sample_data.xml
sites/all/modules/civicrm/sql/test_data.mysql
sites/all/modules/civicrm/sql/test_data_second_domain.mysql
sites/all/modules/civicrm/sql/trigger.mysql
sites/all/modules/civicrm/sql/upgrade_pcm.mysql
sites/all/modules/civicrm/sql/webtest_data.mysql
sites/all/modules/civicrm/sql/zipcodes.mysql
sites/all/modules/civicrm/tests
sites/all/modules/civicrm/tools
sites/all/modules/civicrm/xml"

long_log "Deleting un-needed source files." info
cd "$source_platform_path_temp"
for file in $delete; do
  [ -e "$file" ] && rm -rf "$file"
done

long_log "Moving platform into place." info
# mktemp will restrict read access - we need to ensure www-data on the
# container can read it.
chmod 0755 "$source_platform_path_temp"

# If the platform doesn't already exist - move it into place and we are done. 
if [ ! -d "$source_platform_path" ]; then
  mv "$source_platform_path_temp" "$source_platform_path"
else
  # It would be nice to do an atomic move, however, if the platform is being
  # used by a running container, we can't just move it out of the way. So, we
  # have to rsync and deal with the possibility that there may be a weird error
  # while the sync'ing is happened. I learned about the proper rsync arguments
  # by reading the output of `aubrsync -h`.
  rsync -aHSx --devices --specials --delete-before \
    "${source_platform_path_temp}/" \
    "${source_platform_path}/" 
fi

# Clean up.
rm -rf "$source_platform_path_temp"

# If we have frontends to sync with (that are not us)
host=$(hostname)
frontends="$LONG_LIVE_FRONTENDS"
if [[ $(echo "$frontends" | wc -w) -gt "1" ]]; then
  long_prompt "rsync'ing platform to other frontends. "
  if [ "$reply" == "y" ]; then
    for frontend in $frontends; do
      if [ "$frontend" != "$host" ]; then
        long_log "rsync'ing to %s\n" "info" "$frontend"
        rsync -a --delete "${source_platform_path}/" "aegir@${frontend}.mayfirst.org:${source_platform_path}/"
        if [ "$?" != "0" ]; then
          long_die "Failed to sync to %s" 1 "$frontend"
        fi
      fi
    done
  fi
else
  long_log "No frontends to rsync with." "info"
fi

