#!/bin/bash

long_usage_message="usage: $(basename $0) sibling-backup
Sync backups from this sibling to the other siblings."

long_check_args "$2" "$#" 0
host=$(hostname)
backups_path="/srv/longshore/ptp-backups/${host}"

for sibling in $LONG_SIBLINGS; do
  rsync -a --delete --exclude '*lost+found' "${backups_path}/" ${sibling}.mayfirst.org:"${backups_path}/"
done

