#!/bin/bash

long_usage_message="usage: $(basename $0) sibling-backup
Sync backups from this sibling to the other siblings."

long_check_args "$2" "$#" 0

if [ -z "$LONG_BACKUPS" ]; then
  long_die "LONG_BACKUPS is not defined.\n"
fi

host=$(hostname)
backups_path="${LONG_BACKUPS}/${host}"

# We only rsync files younger than 3 months to all servers to save disk space.
# And skip preupgrades - also to save disk space.
for sibling in $LONG_SIBLINGS; do
  find "$backups_path" -type f -mtime -90 ! -name '*preupgrade*' -exec rsync -t "{}" ${sibling}.mayfirst.org:"${backups_path}/" \;
done

