#!/bin/bash

long_usage_message="usage: $(basename $0) site-fixperms <site>
Ensure the given site has the proper permissions set. This must be run 
as root. 

Arguments
  <site> - The site for which you want to fix the permissions, e.g. ptp."

long_check_args "$2" "$#" 1

site="$2"

# Ensure we are root
iam=$(whoami)

if [ "$iam" != "root" ]; then
  long_die "This script must be run as root."
fi

long_create_site_directories "$site"
