#!/bin/bash

long_usage_message="usage: $(basename $0) site-cc <site>
Really clear all caches, including js/css and templates. 

Arguments
  <site> - The site you want to clear the cache for, e.g. ptp"

long_check_args "$2" "$#" 1

site="$2"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_rerun_over_network "$@" && exit
long_exec_drush_cmd "$site" "cc all"
long_exec_in_container "$site" "rm -rf \
  /var/www/powerbase/sites/default/files/css \
  /var/www/powerbase/sites/default/files/js \
  /var/www/powerbase/sites/default/files/civicrm/templates_c/en_US"

