#!/bin/bash

long_usage_message="usage: $(basename $0) site-provision <site> [<platform>] [<db>] 
Provision a site. This is a single command to create a new site from scratch
and start it. It handles site-create, site-setup and site-configure.  

Arguments
  <site> - The site you want to create, e.g. ptp 
  <platform> - The platform you want this site to use. If blank, use default.
    You can also pass the path to the platform.
  <db> - The db container you want to link this site to. If blank, use default."

long_check_args "$2" "$#" 1

site="$2"
# Platform can either be the name or the path. But, we want the name.
platform=$(basename "$3")
db="$4"

if [ -z "$db" ]; then
  long_set_default_db "$site"
  db="$LONG_DEFAULT_DB"
fi

[ -z "$platform" ] && platform="$LONG_DEFAULT_PLATFORM"

long_log "Site: %s, DB: %s, Platform: %s\n" info "$site" "$db" "$platform"
long_create_container site "$site" "$db" "$platform"
docker start "$site"
#long_create_dns "$site"
long_setup_site "$site"
long_initialize_site "$site"
#long_setup_org_info "$site"
long_exec_cv_cmd "$site" ext:upgrade-db 
long_add_demo_theme "$site"
long_nginx_reload

# Clear the cache to avoid the mosaico engine error.
long_clear_cache "$site"
