#!/bin/bash

long_usage_message="usage: $(basename $0) site-create <site> [<db>] [<platform>]
Create a site. This is a thin wrapper around container-create for sites. 

Arguments
  <site> - The site you want to create, e.g. ptp 
  <db> - The db container you want to link this site to. If blank, use default.
  <platform> - The platform you want this site to use. If blank, use default"

long_check_args "$2" "$#" 1

site="$2"
db="$3"
platform="$4"

[ -z "$db" ] && db="$LONG_DEFAULT_DB"
[ -z "$platform" ] && platform="$LONG_DEFAULT_PLATFORM"

# Do not re-run over the network! We should only be calling site-create
# and site-provision on the sibling that we want the site.
long_create_container site "$site" "$db" "$platform"
long_nginx_reload

