#!/bin/bash

long_usage_message="usage: $(basename $0) site-theme <site> [<theme-name>]
Create the base template files for a theme for the given site.

Arguments
 <site> - subdomain of the site you'd like to have the theme.
 <theme-name> - optionally provide a name for the theme (by default
   a theme with the same name as the subdomain is created. This 
   argument is required if you have  more than one theme."

long_check_args "$2" "$#" 1

site="$2"
name="$3"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"

long_rerun_over_network "$@" && exit

# If the site is not running we can't setup the theme.
if ! long_container_running "$site"; then
  long_die "Not running for %s because it is not running." 1 "$site"
fi

# If the theme name is ommitted, use the name of the site.
[ -z "$name" ] && name="$site"

if [[ ! $name =~ ^[a-z0-9_]+$ ]]; then
  long_die "Only letters and numbers are allowed in the theme name. You entered %s." 1 "$name"
fi

path="${LONG_SRV}/services/sites/${site}/drupal"
theme_path="$path/themes/$name"
if [  -d "$theme_path" ]; then
  long_prompt "A theme with that name already exists. Do you want to run pbd-prepare-theme on it?"
  if [ "$reply" = "y" ]; then
    long_exec_drush_cmd "$site" "pbd-prepare-theme --name=$name"
    exit
  else
    long_die "Please choose a different theme name."
  fi
fi
mkdir -p "$theme_path"

homepage="http://${site}.org/"

# Info page
cat > "${theme_path}/${name}.info" <<EOF
name = $name 
description = $name Subtheme
base theme = civiresponsive 
core = 7.x
engine = phptemplate

stylesheets[all][] = $name.css

;;;;;;;;;;;;;;;;;;;;;
;; Regions
;;;;;;;;;;;;;;;;;;;;;

regions[navigation]     = 'Navigation'
regions[header]         = 'Top Bar'
regions[highlighted]    = 'Highlighted'
regions[help]           = 'Help'
regions[content]        = 'Content'
regions[sidebar_first]  = 'Primary'
regions[sidebar_second] = 'Secondary'
regions[footer]         = 'Footer'
regions[page_top]       = 'Page top'
regions[page_bottom]    = 'Page bottom'

settings[bootstrap_cdn] = ''
EOF

# optional template.php page
cat > "${theme_path}/template.php" <<EOF
<?php

/** 
 * This function replaces the home page link at the top of the them
 * with an alternate URL to users are directed to the group's actual
 * home page rather than the PowerBase home page.
 *
 * Uncomment the function lines and edit to enable.
 **/
function ${name}_preprocess_page(&\$variables) {
  \$variables['front_page'] = '$homepage';
}
EOF

cat > "${theme_path}/$name.css" <<EOF
/** See https://support.ourpowerbase.net/wiki/create-custom-theme **/
EOF

long_exec_drush_cmd "$site" "pbd-prepare-theme --name=$name"

long_prompt "Your theme ($name) has been created. Would you like to edit the css file now?"
if [ "$reply" = "y" ]; then
  editor "${theme_path}/$name.css"
fi
