#!/bin/bash

long_usage_message="usage: $(basename $0) [<site>]
Start the given site container and all linked db containers.

Arguments
  <site> - The site to start. If left out, start all containers"

long_check_args "$2" "$#" 0

sites="$2"

if [ -z "$sites" ]; then
  long_set_sites
  sites="$LONG_SITES"
fi

for site in $sites; do
  long_container_up site "$site"
done
long_nginx_reload
