#!/bin/bash

long_usage_message="usage: $(basename $0) site-convert <site> <backup-file> [<db>] [<platform>]
Setup new site based on an aegir backup file. You have to first put the
site in maintenance mode and then backup it up via aegir.

Arguments
  <site> - The site to fetch the data for.
  <backup-file> - The aegir backup file to pull from.
  <db> - The db container to use.
  <platform> - The platform to use."

long_check_args "$2" "$#" 2

site="$2"
backup="$3"
db="$4"
platform="$5"

[ -z "$db" ] && db="$LONG_DEFAULT_DB"
[ -z "$platform" ] && platform="$LONG_DEFAULT_PLATFORM"

[ ! -f "$backup" ] && long_die "Backup file doesn't exist."


long_log "Unpacking backup file." info
temp=$(mktemp -d)
cd "$temp"
tar -xzf "$backup"

long_log "Making basic directory structure." info

site_dir="${LONG_SRV}/services/sites/${site}"
mkdir -p "${site_dir}/drupal"
mkdir -p "${site_dir}/backup"

long_log "Putting database dump in place." info
cat ./database.sql | gzip --to-stdout > "${site_dir}/backup/${site}.sql.gz"

long_log "Removing extensions directory." info
rm -rf custom-civicrm/extensions

long_log "Putting directories in place." info
# In case we are running twice, remove the target destination to avoid 
# errors. We assume the backup is the desired source and anything in 
# the target is left over from a failed attempt.
for foo in custom-civicrm themes modules files private; do
  if [ -d "${site_dir}/drupal/$foo" ]; then
    long_log "Deleting existing directory (%s)" info "$foo" 
    rm -rf "${site_dir}/drupal/$foo";
  fi
  mv "$foo" "${site_dir}/drupal/"
done

long_log "Removing temp directory"

# Change directories before deleting the temp dir to avoid "getcwd()" errors.
cd "${LONG_SRV}"

# Delete now - we may have an error later and we don't want this 
# potentially huge directory left around in tmp.
rm -rf "$temp"

# Before we create the container, we have to ensure that all the files in
# private and files are world readable and executeable. long_create_container
# will ensure that the proper permissions are set, but it expects all files to
# be world-readable and that's not necessarily the case when coming from aegir.
chmod -R o+xr "${site_dir}/drupal/files"
chmod -R o+xr "${site_dir}/drupal/private"

long_log "Provisioning site via longshore"
long_create_container site "$site" "$db" "$platform"
docker start "$site"
long_setup_site "$site"
long_configure_site "$site"
long_nginx_reload

# Lastly, ensure we are not in maintenance mode any more.
long_exec_drush_cmd "$site" "vset maintenance_mode 0"

long_log "Changing DNS record."
long_create_dns "$site"


