#!/bin/bash

long_usage_message="usage: $(basename $0) <site>
Start the given site container and all linked db containers.

Arguments
  <site> - The site to start."

long_check_args "$2" "$#" 1

site="$2"
long_container_up site "$site"
long_nginx_reload
