#!/bin/bash

long_usage_message="usage: $(basename $0) site-configure <site> [once|once-force]
Configure the site to be a PowerBase site. Enable all modules, themes,
and extensions. Configure all settings. Optionally set the:
LONG_SET_IMAP_PASSWORD env variable to any value to force the IMAP
password to be reset.

Arguments
  <site> - The site to configure.
  [once|once-force] - Optionally pass once to indicate that you want to run the one time
    configuration settings instead of the regular configuration settings. Pass once-force
    to run it even if it has already been run."

long_check_args "$2" "$#" 1

site="$2"
once="$3"

if [ -n "$once" -a "$once" != "once" -a "$once" != "once-force" ]; then
  long_die "I think you meant to pass once or once-force as the third argument but something else came through."
fi

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_rerun_over_network "$@" && exit

if [ "$once" = "once" ]; then
  long_configure_site_once "$site"
elif [ "$once" = "once-force" ]; then
  long_configure_site_once "$site" force
else
  long_configure_site "$site"
fi

# Clear cache for good measure and to avoid mosaico missing graphics driver error.
long_clear_cache "$site" all 
