#!/bin/bash

long_usage_message="usage: $(basename $0) site-setup <site>
Install drupal/civicrm if necessary and configure all paths and settings
required for the basic operations of the site.

Arguments
  <site> - The site to setup."

long_check_args "$2" "$#" 1

site="$2"
long_setup_site "$site"
