#!/bin/bash

long_usage_message="usage: $(basename $0) site-updatedb [<site>]
Run all Drupal and CiviCRM database updates on the given site.

Arguments
  <site> - The site to update. If left out, update all sites."

long_check_args "$2" "$#" 0

sites="$2"

if [ -z "$sites" ]; then
  long_set_sites
  sites="$LONG_SITES"
fi

for site in $sites; do
  long_rerun_over_network site-updatedb "$site" && continue
  if ! long_container_running "$site"; then
    long_log "Not running on %s because container is not up." error "$site"
    continue
  fi
  long_log "Updating drupal on %s" info "$site"
  long_exec_drush_cmd "$site" "-y updatedb"
  long_log "Updating CiviCRM Core on %s" info "$site"
  long_exec_drush_cmd "$site" "-y civicrm-upgrade-db"
  long_exec_drush_cmd "$site" "pbd-rebuild-multilingual-schema"
  long_log "Updating CiviCRM Extensions on %s" info "$site"
  long_exec_cv_cmd "$site" "ext:upgrade-db"
done
