#!/bin/bash

long_usage_message="usage: $(basename $0) site-sqlc <site>
Long into the site's database with the site level database permissions.

Arguments
  <site> - The site database to login to."

long_check_args "$2" "$#" 1

site="$2"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_rerun_over_network "$@" && exit
long_enter_site_database "$site"
