#!/bin/bash

long_usage_message="usage: $(basename $0) site-dns <site>
Create or update a DNS A record for the given site. 

Arguments
  <site> - The site you want to create the IP address for, e.g. ptp"

long_check_args "$2" "$#" 1

site="$2"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_create_dns "$site"

