#!/bin/bash

long_usage_message="usage: $(basename $0) fetch <site>
Copy all data from the live version of the site.

Arguments
  <site> - The site to fetch the data for."

long_check_args "$2" "$#" 1

site="$2"

if [ "$LONG_LIVE" = "y" ]; then
  long_die "Only run site-fetch on a dev instance."
fi
long_fetch_site "$site"

# We have to create site directories to ensure permissions are properly
# set.
long_create_site_directories "$site"

