#!/bin/bash

long_usage_message="usage: $(basename $0) site-reachable [<site>]
Check to see if the given site is accessible via https.

Arguments
  <site> - Optionally, pass the site you want to check. If empty, check all sites."

long_check_args "$2" "$#" 0

sites="$2"

if [ -z "$sites" ]; then
  long_set_sites
  sites="$LONG_SITES"
  for sibling in $LONG_SIBLINGS; do
    more_sites=$(ssh ${sibling}.mayfirst.org '/srv/longshore/bin/longshore site-list')
    sites="$sites $more_sites"
  done
fi
timeout=10
for site in $sites; do
  long_log "Checking %s" info "$site"
  if ! wget --timeout="$timeout" https://${site}.ourpowerbase.net -O- 2>&1 | grep "ERROR 403:" >/dev/null; then
    long_log "Site %s is offline." error "$site"
  fi
done


