#!/bin/bash

long_usage_message="usage: $(basename $0) afetch <site>
Pulling a live aegir site.

Arguments
  <site> - The site to fetch the data for."

long_check_args "$2" "$#" 1

site="$2"

long_afetch_site "$site"


