#!/bin/bash

long_usage_message="usage: $(basename $0) site-sqlt <site> <thread-id>
Either output a list of current MySQL threads (without <thread-id>) or kill
the thread represented by thread id <thread-id>.

This command is useful for debugging slow database problems because it can
reveal queries that are running for a long time.

Arguments
  <site> - The site database to run agaist.
  <thread-id> - Optionally, pass the SQL thread id to kill."

long_check_args "$2" "$#" 1

site="$2"

declare -i thread_id
thread_id="$3"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"

if [ "$thread_id" -eq "0" ]; then
  (/srv/longshore/bin/longshore site-sqlq "$site" "SHOW PROCESSLIST") | column -t
else
  (/srv/longshore/bin/longshore site-sqlq "$site" "KILL '$thread_id'")
fi
