#!/bin/bash

long_usage_message="usage: $(basename $0) site-extension-status <site> <extension>
Return the status of the given extension, module or theme.

Arguments
  <site> - The site database to run the query or --all for all sites.
  <extension> - The name of the extension, module or theme to check."

long_check_args "$2" "$#" 2

# Generate list of sites to run on if necessary.
if [ "$2" != "--all" ]; then
  sites="$2"
else
  long_set_sites "$(hostname)"
  sites="$LONG_SITES" 
fi

extension="$3"

enabled=0
disabled=0
notinstalled=0
extension_status=unknown

for site in $sites; do
  long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
  temp=$(mktemp)
  echo "SELECT is_active FROM civicrm_extension WHERE full_name = '$extension'" > "$temp"
  out=$(long_execute_site_query "$site" "$temp" | tail -n1)
  rm "$temp"
  if [ -z "$out"  ]; then
    extension_status="not installed"
    notinstalled=$(( "$notinstalled" + 1 ))
  elif [ "$out" = "1" ]; then
    extension_status="enabled"
    enabled=$(( "$enabled" + 1 ))
  else
    extension_status="disabled"
    disabled=$(( "$disabled" + 1 ))
  fi
  printf "%s: %s\n" "$site" "$extension_status" 
done

printf "\n======\n"
printf "Total Enabled: %s\n" "$enabled"
printf "Total Disabled: %s\n" "$disabled"
printf "Total Not Installed: %s\n" "$notinstalled"
printf "\n======\n"


