#!/bin/bash

long_usage_message="usage: $(basename $0) site-log <site> [follow]
Pipe the current ConfigAndLog file to less.

Arguments
  <site> - The site on which to report.
  follow - tail -f the file instead of piping to less"

long_check_args "$2" "$#" 1

site="$2"
follow="$3"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_rerun_over_network "$@" && exit

# Find the right log
path="${LONG_SRV}/services/sites/$site/drupal/files/civicrm/ConfigAndLog/"
log=$(ls -t "$path"/CiviCRM.*.log | head -n1)
if [ -n "$follow" ]; then
  if [ "$follow" = "follow" ]; then
    tail -f "$log"
  else
    long_die "I think you meant to pass follow as the last argument."
  fi
else
  less "$log"
fi
