#!/bin/bash

long_usage_message="usage: $(basename $0) site-configure <site>
Configure the site to be a PowerBase site. Enable all modules, themes,
and extensions. Configure all settings. Optionally set the:
LONG_SET_IMAP_PASSWORD env variable to any value to force the IMAP
password to be reset.

Arguments
  <site> - The site to configure."

long_check_args "$2" "$#" 1

site="$2"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_rerun_over_network "$@" && exit
long_configure_site "$site"
