#!/bin/bash

long_usage_message="usage: $(basename $0) site-d8 <site> platform 
Provision a d8 version of a site. Pass in the site name of the existing
(d7) site. The new site will have d8 appended
to the domain name (e.g. ptpd8.ourpowerbase.net).

Arguments
  <site> - The site you want to provision a d8 site for, e.g. ptp 
  <platform> - The platform you want this site to use.
"
long_check_args "$2" "$#" 2

d7site="$2"
d8site="${d7site}d8"
# Platform can either be the name or the path. But, we want the name.
platform=$(basename "$3" .json)

long_set_default_db "$site"
db="$LONG_DEFAULT_DB"

long_log "D7 Site: %s, D8 Site: %s DB: %s, Platform: %s\n" info "$d7site" "$d8site" "$db" "$platform"
long_create_container site "$d8site" "$db" "$platform"
docker start "$d8site"

# Clear the cache before backing up.
long_clear_cache "$d7site" all

# Dump the CiviCRM tables from the d7 site to a backup file in the d8 site directory.
civicrm_backup="/srv/longshore/services/sites/${d8site}/backup/${d8site}.civicrm.sql"
defaults_file="--defaults-file=/srv/longshore/etc/my.cnf"
long_log "Dumping CiviCRM tables from %s to %s" info "$d7site" "$civicrm_backup"
mysqldump "$defaults_file" ptp $(mysql "$defaults_file" --database "$d7site" --batch --silent --execute "SHOW TABLES LIKE 'civi%'") > "$civicrm_backup"

# Install fresh civicrm and drupal.
long_setup_site "$d8site"

# These are the drupal only pieces of long_initialize_site:
# Populate the $LONG_SITE_TMP_VAR variable which is used to execute
# commands in the container.
long_init_site_tmp_var "$d8site"

# install lsd module for drupal 8+
long_exec_drush_cmd "$d8site" "pm:enable lsd"

# Set drupal initial settings. 
long_exec_drush_cmd "$d8site" "lsd-initialize"

# Overwrite civi tables with d7 ones.
long_log "Importing CiviCRM tables" info
long_execute_site_query "$d8site" "$civicrm_backup"

# Set the proper value for the extensions directory so we can call the setup extension.
temp=$(mktemp)
printf "UPDATE civicrm_setting SET value = '%s' WHERE name = 'extensionsDir';" 's:21:"[cms.root]/extensions";' > "$temp"
long_execute_site_query "$d8site" "$temp"
rm "$temp"

# Now we have to clear some caches - minimally the drupal cache.
long_clear_cache "$d7site" all

# Now update a few Civi settings that need to be different from D8 sites.
long_exec_cv_cmd "$d8site" "api4" "PowerbaseSetup.InitializeUpgradedSite"

long_create_dns "$d8site"


long_nginx_reload

