#!/bin/bash

long_usage_message="usage: $(basename $0) site-info <site>
Print all details about this site, including password.

Arguments
  <site> - The site on which to report."

long_check_args "$2" "$#" 1

site="$2"

long_rerun_over_network site-info "$site" && exit

mycnf="${LONG_SRV}/services/sites/${site}/my.cnf"
pass=$(grep password= "$mycnf" | cut -d= -f2)
long_get_db_for_site "$site"

printf "Site: %s\nPassword: %s\nDB: %s\nPHPMyAdmin URL: %s\nHost: %s\n" \
  "$site" "$pass"  "$LONG_DB_HOST" "$LONG_PHPMYADMIN_URL" "$(hostname)"
