#!/bin/bash

long_usage_message="usage: $(basename $0) site-pull <site> [<db>] [<platform>]

Pull in a live site and then provision it locally. This is a single command,
designed to be used on a dev server only, to create a new site and start it. It
handles site-create, site-setup and site-configure.  

Arguments
  <site> - The site you want to create, e.g. ptp 
  <db> - The db container you want to link this site to. If blank, use default.
  <platform> - The platform you want this site to use. If blank, use default"

long_check_args "$2" "$#" 1

site="$2"
db="$3"
platform="$4"

if [ -z "$db" ]; then 
  long_set_default_db "$site"
  db="$LONG_DEFAULT_DB"
fi

[ -z "$platform" ] && platform="$LONG_DEFAULT_PLATFORM"

long_fetch_site "$site"
long_create_container site "$site" "$db" "$platform"
docker start "$site"
long_setup_site "$site"
long_configure_site "$site"
long_nginx_reload

