#!/bin/bash

long_usage_message="usage: $(basename $0) site-cc <site> [cache]
Really clear all caches, including js/css, templates and
flood table for blocked logins. 

Arguments
  <site> - The site you want to clear the cache for, e.g. ptp
  <cache> - Optionally only clear the specificed cache, values 
    can be drush (for all drush controlled caches), menu (
    for the CiviCRM menu), files (for all css/js/template 
    files, extensions, and flood, for the drupal flood table (user login
    blocks for incorrect password)."

long_check_args "$2" "$#" 1

site="$2"
cache="$3"

if [ -z "$cache" ]; then
  cache=all
fi

if [ "$cache" != "drush" -a \
  "$cache" != "menu" -a \
  "$cache" != "files" -a \
  "$cache" != "flood" -a \
  "$cache" != "extensions" -a \
  "$cache" != "reconcile" -a \
  "$cache" != "all" ]; then
  long_die "I don't know how to clear that cache."
fi

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_rerun_over_network "$@" && exit

long_clear_cache "$site" "$cache"
