#!/bin/bash

long_usage_message="usage: $(basename $0) site-cmd <site>
Launch an interactive bash shell in the given site as the www-data user..

Arguments
  <site> - Pass the site if you only want to run the command on that site."

long_check_args "$2" "$#" 1

# Run for all local sites
hostname=$(hostname)

site="$2"

long_check_site_exists "$site" || long_die "Site doesn't exist (%s)." 1 "$site"
long_rerun_over_network "$@" && exit

# If the site is not running we can't run a command.
if ! long_container_running "$site"; then
  long_die "Not executing command for %s because it is not running." 1 "$site"
fi

long_enter_site "$site"
