#!/bin/bash

long_usage_message="usage: $(basename $0) site-convert <site> [<db>] [<platform>]
Setup new site based on an aegir backup file. You have to first put the
site in maintenance mode and then backup it up via aegir.

Arguments
  <site> - The site to fetch the data for.
  <db> - The db container to use.
  <platform> - The platform to use."

long_check_args "$2" "$#" 2

site="$2"
backup="$3"
db="$4"
platform="$5"

[ -z "$db" ] && db="$LONG_DEFAULT_DB"
[ -z "$platform" ] && platform="$LONG_DEFAULT_PLATFORM"

[ ! -f "$backup" ] && long_die "Backup file doesn't exist."

long_log "Changing DNS record."
long_create_dns "$site"

long_log "Unpacking backup file." info
temp=$(mktemp -d)
cd "$temp"
tar -xzf "$backup"

long_log "Making basic directory structure." info

site_dir="${LONG_SRV}/services/sites/${site}"
mkdir -p "${site_dir}/drupal"
mkdir "${site_dir}/backup"

long_log "Putting database dump in place." info
cat ./database.sql | gzip --to-stdout > "${site_dir}/backup/${site}.sql.gz"

long_log "Removing extensions directory." info
rm -rf custom-civicrm/extensions

long_log "Putting directories in place." info
mv custom-civicrm themes modules files private "${site_dir}/drupal/"

long_log "Removing temp directory"

# Change directories before deleting the temp dir to avoid "getcwd()" errors.
cd "${LONG_SRV}"

# Delete now - we may have an error later and we don't want this 
# potentially huge directory left around in tmp.
rm -rf "$temp"

long_log "Provisioning site via longshore"
long_create_container site "$site" "$db" "$platform"
docker start "$site"
long_setup_site "$site"
long_configure_site "$site"
long_nginx_reload

# Lastly, ensure we are not in maintenance mode any more.
long_exec_drush_cmd "$site" "vset maintenance_mode 0"



