#!/bin/bash

long_usage_message="usage: $(basename $0) site-migrate <site> <new-platform>
Migrate the site from it's current platform to a new platform.

Arguments
  <site> - The site to migrate.
  <platform> - The name or path to the new platform."

long_check_args "$2" "$#" 2

site="$2"
new_platform=$(basename "$3")

# Run some sanity checks.
if ! long_check_site_exists "$site"; then
  long_die "Site doesn't exist (%s)." 1 "$site"
fi

if ! long_container_running "$site"; then
  long_die "Please start the site before migrating"
fi

if [ ! -d "${LONG_SRV}/platforms/${new_platform}" ]; then
  long_die "Can't find the new platform (%s)." 1 "$new_platform"
fi

# Record existing platform
long_set_site_platform "$site"
old_platform="$LONG_SITE_PLATFORM"

# Record existing database
long_set_site_db_host "$site"
db_host="$LONG_SITE_DB_HOST"

if [ -z "$db_host" ]; then
  long_die "Can't determine current database host."
fi

if [ -z "$old_platform" ]; then
  long_die "Can't determine current platform."
fi

if [ "$new_platform" = "$old_platform" ]; then
  long_log "Site is already running that platform." error
  long_prompt ""
  [ "$reply" != "y" ] && long_die "Not continuing." 0
fi

# Remove reportbase - it is no longer needed and has been removed
# from the 4.6 platform. NOTE: this should be removed after the 4.6 
# upgrade.
if [ "$new_platform" = "ourpowerbase-d7-c4.6" ]; then
  long_prompt "Disable/Uninstall reportbase"
  if [ "$reply" = "y" ]; then
    long_exec_drush_cmd "$site" \
      "php-eval '_civicrm_init(); civicrm_api3(\"extension\", \"disable\", array(\"keys\" => array(\"nz.co.fuzion.reportbase\")));'"
    long_exec_drush_cmd "$site" \
      "php-eval '_civicrm_init(); civicrm_api3(\"extension\", \"uninstall\", array(\"keys\" => array(\"nz.co.fuzion.reportbase\")));'"
  fi

  # This action seems to have been in Drupal 6 and was not properly cleaned up.
  long_prompt "Remove orphaned action"
  if [ "$reply" = "y" ]; then
    sqlfile=$(mktemp)
    echo "DELETE FROM actions WHERE callback = 'user_block_ip_action'" > "$sqlfile"
    long_execute_site_query "$site" "$sqlfile"
    rm "$sqlfile"
  fi
fi

# Empty sessions table for quicker restore and to ensure everyone is 
# logged out for upgrade.
long_prompt "Truncating sessions table"
[ "$reply" = "y" ] && long_clear_sessions "$site"

# Make a backup so we can restore in case of error. If backup fails exit
# with error.
long_prompt "Making a backup..."
if [ "$reply" = "y" ]; then
  (longshore site-backup "$site" "preupgrade") || long_die "Failed to backup site."
fi

long_prompt "Entering maintenance mode..."
[ "$reply" = "y" ] && long_exec_drush_cmd "$site" "-y vset maintenance_mode 1"

long_prompt "Stopping and removing site container..."
if [ "$reply" = "y" ]; then
  docker stop "$site"
  docker rm "$site"
fi

long_prompt "Launching new container with new platform"
[ "$reply" = "y" ] && long_container_up site "$site" "$db_host" "$new_platform"

long_prompt "Reload nginx"
[ "$reply" = "y" ] && long_nginx_reload 

# Run the upgrade in a loop - so if there is a failure we can
# restore the database and try again.
while [ 1 ]; do 
  # Don't use long_prompt - we don't want it to be possible to automate
  # the answers to these questions.
  long_always_prompt "Upgrading civicrm database..."
  if [ "$reply" = "y" ]; then
    long_exec_drush_cmd "$site" "-y civicrm-upgrade-db" 

    long_always_prompt "Was the upgrade successful?"
    [ "$reply" = "y" ] && break
    long_always_prompt "Restore database from backup so you can try again?"
    if [ "$reply" = "y" ]; then
      long_log "Importing from backup. This will take a while" info
      (longshore site-import "$site") || long_die "Failed to restore the backup."

      long_always_prompt "Entering maintenance mode..."
      [ "$reply" = "y" ] && long_exec_drush_cmd "$site" "-y vset maintenance_mode 1"
    fi
  else
    # If we are not upgrading, break out of while loop.
    break
  fi
done

long_prompt "Removing maintenance mode..."
[ "$reply" = "y" ] && long_exec_drush_cmd "$site" "-y vset maintenance_mode 0"

long_prompt "Running site-configure..."
[ "$reply" = "y" ] && long_configure_site "$site" 
