#!/bin/bash

long_usage_message="usage: $(basename $0) site-dkim <site> <domain> [<selector>]
Generate a DKIM key and add the appropriate DNS txt record.

Arguments
  <site> - The site you want to generate and configure the dkim record fo for, e.g. ptp
  <domain> - The domain used by the group to send emails (e.g. progressivetech.org)
  <selector> - Optionally provide the selector. Defaults to pb1. Pass selector if you
    want to create multiple DKIM records so users can send from multiple domains."

long_check_args "$2" "$#" 2

site="$2"
domain="$3"
selector="$4"

if [ -z "$selector" ]; then
  selector=pb1
fi

fqdn="${selector}.domainkey.${site}.ourpowerbase.net"

if ! long_check_site_exists "$site"; then 
  long_prompt "The ${siate} does not exist. You can still make the dkim record for domain ${fqdn} and address ${domain}."
  if [ "$reply" != "y" ]; then
    long_log "Not continuing." info
    exit 0
  fi
fi

long_generate_dkim_key "$domain" "$selector"

if [ -n "$LONG_SITE_DKIM_TXT" ]; then
  long_create_dkim_dns "$fqdn" "$LONG_SITE_DKIM_TXT"
else
  long_die "Not configuring DNS for empty DKIM txt record."
fi

