#!/usr/bin/php
<?php
# This script takes our drush make file and generates an snippet to add to our
# composer file.

$path = NULL;

if (isset($_SERVER['argv'][1])) {
  $path = $_SERVER['argv'][1];
}

if(!file_exists($path)) {
  echo "Can't find file '$path'\n";
  exit(1);
}
$extensions = [];
$regexp = '#^projects\[([a-zA-Z_]+)\]\[(destination|download)\](\[(url|revision)\])? = "(.*)"#';
$lines = file($path);

foreach ($lines as $line) {
  if (preg_match($regexp, $line, $matches)) {
    $name = $matches[1];
    $line_type = $matches[2];
    $var_type = $matches[4];
    $value = $matches[5];
    // echo "$name $line_type $var_type $value\n";
    if ($line_type == 'destination') {
      if ($value == 'extensions') {
        // We want this one, so add the key.
        $extensions[$name] = [];
      }
      // We don't want this line - we just needed to make sure it's an extension.
      continue;
    }
    if (array_key_exists($name, $extensions)) {
      if ($var_type == 'url') {
        // Fix ptp git urls
        $value = str_replace('git://git.progressivetech.org', 'https://git.progressivetech.org', $value);
        // Add the directory name.
        // The mosaico URL is a zip file. Needs special attention.
        if (preg_match('/uk\.co\.vedaconsulting\.mosaico/', $value)) {
          $basename = 'uk.co.vedaconsulting.mosaico';
          $type = 'archive';
          $extensions[$name]['revision'] = NULL;
        }
        else {
          $type = 'git';
          $url_parts = parse_url($value);
          $basename = basename($url_parts['path'], '.git');
        }
        $extensions[$name]['dir'] = $basename;
        $extensions[$name]['type'] = $type;
      }
      $extensions[$name][$var_type] = $value;
    }
  }
}

echo "        \"downloads\": {\n";
foreach($extensions as $name => $extension) {
  $type = $extension['type'];
  $dir = $extension['dir'];
  $url = $extension['url'];
  $revision = $extension['revision'];
  if ($revision) {
    $url = "${url}@${revision}";
  }
  echo "            \"$name\": {\n";
  echo "                \"url\": \"$url\",\n";
  echo "                \"path\": \"web/extensioins/$name\",\n";
  echo "                \"type\": \"$type\"\n";
  echo "            },\n";
}
echo "        }\n";
echo "    }\n";
echo "}\n";
