#!/usr/bin/php
<?php
# This script takes our drush make file and generates an snippet to add to our
# composer file.

$path = NULL;

if (isset($_SERVER['argv'][1])) {
  $path = $_SERVER['argv'][1];
}

if(!file_exists($path)) {
  echo "Can't find file '$path'\n";
  exit(1);
}
$extensions = [];
$regexp = '#^projects\[([a-zA-Z_]+)\]\[(destination|download)\](\[(url|revision)\])? = "(.*)"#';
$lines = file($path);

foreach ($lines as $line) {
  if (preg_match($regexp, $line, $matches)) {
    $name = $matches[1];
    $line_type = $matches[2];
    $var_type = $matches[4];
    $value = $matches[5];
    // echo "$name $line_type $var_type $value\n";
    if ($line_type == 'destination') {
      if ($value == 'extensions' || $value == 'templates/mosaico_tpl') {
        // We want this one, so add the key.
        $extensions[$name] = [];
      }
    }
    if (array_key_exists($name, $extensions)) {
      if ($line_type == 'download') {
        if ($var_type == 'url') {
          // Fix ptp git urls
          $value = str_replace('git://git.progressivetech.org', 'https://git.progressivetech.org', $value);
          // Add the directory name.
          // The mosaico URL is a zip file. Needs special attention.
          if (preg_match('/uk\.co\.vedaconsulting\.mosaico/', $value)) {
            $type = 'archive';
            $extensions[$name]['revision'] = NULL;
          }
          elseif (preg_match('/org\.civicrm\.shoreditch/', $value)) {
            $value = 'https://github.com/coopsymbiotic/shoreditch';
            $extensions[$name]['revision'] = 'f9f50a1c4fbd8da98cefa37c011179eec98c8daa'; 
          }
          else {
            $type = 'git';
          }
          $extensions[$name]['type'] = $type;
        }
      }
      elseif ($line_type == 'destination') {
        $extensions[$name]['dir'] = "web/${value}/${name}";
      }
      if (!array_key_exists($var_type, $extensions[$name])) {
        $extensions[$name][$var_type] = $value;
      }
    }
  }
}

echo "        \"downloads\": {\n";
$i = 0;
$count = count($extensions);
foreach($extensions as $name => $extension) {
  $i++;
  $type = $extension['type'];
  $dir = $extension['dir'];
  $url = $extension['url'];
  $revision = $extension['revision'];
  if ($revision) {
    $url = "${url}@${revision}";
  }
  $trailing_comma = ',';
  if ($i == $count) {
    // No comma on the last one.
    $trailing_comma = '';
  }
  echo "            \"$name\": {\n";
  echo "                \"url\": \"$url\",\n";
  echo "                \"path\": \"$dir\",\n";
  echo "                \"type\": \"$type\"\n";
  echo "            }${trailing_comma}\n";
}
echo "        }\n";
echo "    }\n";
echo "}\n";
