#!/bin/bash -e

# Special script that must be run as root to create base image
# Exit on error (-e)
temp=$(mktemp -d)
echo "Running debootstrap"
debootstrap --variant=minbase jessie "$temp" http://http.us.debian.org/debian/ 
echo "Importing into docker"
cd "$temp" && tar -c . | docker import - my-jessie 
cd
echo "Removing temp directory"
rm -rf "$temp"
