#!/bin/bash -e

# Special script that must be run as root to create base image
# Exit on error (-e)
temp=$(mktemp -d)
echo "Running debootstrap"
debootstrap jessie "$temp"
echo "Importing into docker"
cd "$temp" && tar -c - . | docker import - ptp-base
cd
echo "Removing temp directory"
rm -rf "$temp"
